### PR TITLE
Don't use polysemy-plugin, remove IdempotentLoweringSpec

### PR DESCRIPTION
**Pull request by KingoftheHomeless**
Stop-gap for https://github.com/polysemy-research/polysemy-zoo/issues/65.
This does not address the underlying bug, so I won't close that issue.
This wasn't as much work as I thought it would be.

### CODE REVIEW

**Comment by KingoftheHomeless** [comment]
@adamConnerSax Can you confirm if this works? I personally have issues trying to get 8.10 working with stack.

**Comment by adamConnerSax** [comment]
Looks like it.  I had to do an "allow-newer: ghc-prim" for my case.  Also, I wanted to do "allow-newer: random"--because the newer random is a major performance upgrade--but then I got a compilation error:
```haskell

**Comment by adamConnerSax** [comment]
So maybe, while you're there, it's worth bumping all the bounds, or at least all but random, though if that's easy to fix, it might be worth it...

**Comment by adamConnerSax** [comment]
Anyway, thanks for working on it!

**Comment by KingoftheHomeless** [comment]
Does that do it?

**Comment by KingoftheHomeless** [comment]
Forgot the tests. Those are significantly more hellish to rewrite, so I'm going with enabling the plugin for the tests only.
Also, for some reason Travis now trips up on building `IdempotentLoweringSpec`, compared to in February. I have no idea why. Considering Idempotent Lowering has long since been de-facto deprecated in favour of `Final`, and `ImpredicativeTypes` has unspecified behaviour, I'll simply be removing that test, and not lose any sleep over it.

@adamConnerSax I'll merge this when you confirm this works.

**Comment by adamConnerSax** [comment]
I’ll test tomorrow AM!

**Comment by adamConnerSax** [comment]
All works on my end, thanks!

**Pull request merged**
