### PR TITLE
Add RevState, EndState, and runReaderFixSem 

### LINKED ISSUE #23: FinalState Effect
```haskell
data FinalState s m a where
  GetFinal :: FinalState s m s

makeSem ''FinalState


runFinalState
    :: Member Fixpoint r
    => s
    -> Sem (State s ': FinalState s ': r) a
    -> Sem r a
runFinalState s m = mdo
  ~(s', a) <-
    interpret
      \case
        GetFinal -> pure s'
      (runLazyState s m)
  pure a
```

Get the final value of a state effect.

### PR DESCRIPTION
**Pull request by KingoftheHomeless**
Based upon #46 , so we once we merge #46 in we won't have to rebase this.

This closes #23 . I wonder if we should actually discard `EndState`, seeing how it's just a thin layer over `runReaderFixSem`.

### CODE REVIEW

**Comment by KingoftheHomeless** [comment]
@isovector Should we release `polysemy-zoo` v0.6 before or after this?

**Comment by isovector** [comment]
Your call!

**Comment by KingoftheHomeless** [comment]
In that case, I'll merge this first. I'll prepare the changelog.

**Comment by KingoftheHomeless** [comment]
Just to confirm, you're ok with this? @isovector

**Comment by isovector** [comment]
super cool! also this is the zoo so anything goes! feel free to merge

**Comment by KingoftheHomeless** [comment]
Then the zoo is ready for v0.6

**Pull request merged**
